import type { AdminAsset, ActivityLogEntry } from "./types";

const now = new Date().toISOString();

function makeAsset(id: string, overrides: Partial<AdminAsset>): AdminAsset {
  return {
    id,
    kind: "scan",
    fileName: `demo-asset-${id}.jpg`,
    mime: "image/jpeg",
    sizeBytes: 1024 * 450,
    uploadedAt: now,
    uploadedBy: "archivist",
    blobKey: null,
    checksum: null,
    lifecycle: "uploaded",
    metadata: {
      documentId: id,
      title: `Demo archival document ${id}`,
      date: null,
      language: "en",
      type: "writing",
      topic: ["social rights"],
      collection: "Demo Collection A",
      source: "Demo source — not verified",
      keywords: ["demo", "placeholder"],
      accessRights: "open",
      rightsNote: "Demo rights note",
      provenanceNote: "Demo provenance — not verified",
      completeness: 40,
    },
    history: [{ at: now, role: "archivist", action: "uploaded", detail: "Initial upload" }],
    isDemo: true,
    ...overrides,
  };
}

export const SEED_ASSETS: AdminAsset[] = [
  makeAsset("adm-001", {
    kind: "scan", fileName: "demo-scan-01.jpg", lifecycle: "published",
    checksum: { algo: "SHA-256", hex: "a".repeat(64), computedAt: now },
    metadata: { documentId: "adm-001", title: "Demo archival document 01", date: null, language: "en",
      type: "writing", topic: ["social rights", "equality"], collection: "Demo Collection A",
      source: "Demo source — not verified", keywords: ["rights", "equality"],
      accessRights: "open", rightsNote: "Demo", provenanceNote: "Demo", completeness: 90 },
    ocr: { status: "done", text: "This is sample OCR text for demonstration.", wordConfidence: [],
      engine: "Tesseract (demo)", validated: true, needsSpecialist: false },
    history: [
      { at: now, role: "archivist",      action: "uploaded",      detail: "Initial upload" },
      { at: now, role: "archivist",      action: "ocr-completed", detail: "OCR completed" },
      { at: now, role: "reviewer",       action: "approved",      detail: "Metadata and OCR verified" },
      { at: now, role: "administrator",  action: "published",     detail: "Published to public archive" },
    ],
  }),
  makeAsset("adm-002", {
    kind: "scan", fileName: "demo-scan-02.jpg", lifecycle: "in-review",
    checksum: { algo: "SHA-256", hex: "b".repeat(64), computedAt: now },
    metadata: { documentId: "adm-002", title: "Demo archival document 02", date: null, language: "hi",
      type: "speech", topic: ["education"], collection: "Demo Collection B",
      source: "Demo source — not verified", keywords: ["education", "scholarship"],
      accessRights: "open", rightsNote: "Demo", provenanceNote: "Demo", completeness: 75 },
    ocr: { status: "done", text: "नमूना OCR पाठ प्रदर्शन के लिए।", wordConfidence: [],
      engine: "Tesseract (demo)", validated: false, needsSpecialist: false },
  }),
  makeAsset("adm-003", {
    kind: "scan", fileName: "demo-scan-03.jpg", lifecycle: "ocr-queued",
    metadata: { documentId: "adm-003", title: "Demo archival document 03", date: null, language: "en",
      type: "manuscript", topic: ["legal framework"], collection: "Demo Collection C",
      source: "Demo source — not verified", keywords: ["law", "legal"],
      accessRights: "restricted", rightsNote: "Demo restricted", provenanceNote: "Demo", completeness: 30 },
  }),
  makeAsset("adm-004", {
    kind: "audio", fileName: "demo-audio-01.mp3", mime: "audio/mp3",
    lifecycle: "approved",
    checksum: { algo: "SHA-256", hex: "c".repeat(64), computedAt: now },
    metadata: { documentId: "adm-004", title: "Demo audio record 01", date: null, language: "en",
      type: "speech", topic: ["public address"], collection: "Demo Collection A",
      source: "Demo source — not verified", keywords: ["speech", "audio"],
      accessRights: "open", rightsNote: "Demo", provenanceNote: "Demo", completeness: 80 },
  }),
  makeAsset("adm-005", {
    kind: "video", fileName: "demo-video-01.mp4", mime: "video/mp4",
    lifecycle: "uploaded",
    metadata: { documentId: "adm-005", title: "Demo video record 01", date: null, language: "en",
      type: "record", topic: ["constitutional assembly"], collection: "Demo Collection B",
      source: "Demo source — not verified", keywords: ["video", "documentary"],
      accessRights: "open", rightsNote: "Demo", provenanceNote: "Demo", completeness: 20 },
  }),
  makeAsset("adm-006", {
    kind: "photograph", fileName: "demo-photo-01.jpg", lifecycle: "ocr-done",
    metadata: { documentId: "adm-006", title: "Demo photograph 01", date: null, language: "en",
      type: "photograph", topic: ["archival record"], collection: "Demo Collection C",
      source: "Demo source — not verified", keywords: ["photograph", "image"],
      accessRights: "open", rightsNote: "Demo", provenanceNote: "Demo", completeness: 55 },
  }),
  makeAsset("adm-007", {
    kind: "scan", fileName: "demo-scan-04.jpg", lifecycle: "rejected",
    metadata: { documentId: "adm-007", title: "Demo archival document 04", date: null, language: "mr",
      type: "manuscript", topic: ["social rights"], collection: "Demo Collection A",
      source: "Demo source — not verified", keywords: ["manuscript", "draft"],
      accessRights: "staff-only", rightsNote: "Demo staff-only", provenanceNote: "Demo", completeness: 45 },
    history: [
      { at: now, role: "archivist", action: "uploaded",  detail: "Initial upload" },
      { at: now, role: "reviewer",  action: "rejected",  detail: "Incomplete metadata — sent back" },
    ],
  }),
  makeAsset("adm-008", {
    kind: "scan", fileName: "demo-scan-05.jpg", lifecycle: "in-review",
    checksum: { algo: "SHA-256", hex: "d".repeat(64), computedAt: now },
    metadata: { documentId: "adm-008", title: "Demo archival document 05", date: null, language: "gu",
      type: "debate", topic: ["constitutional assembly", "democracy"], collection: "Demo Collection B",
      source: "Demo source — not verified", keywords: ["debate", "constitution"],
      accessRights: "open", rightsNote: "Demo", provenanceNote: "Demo", completeness: 70 },
    ocr: { status: "done", text: "ગ્રાઉન્ડ OCR ટેક્સ્ટ ઉદાહરણ.", wordConfidence: [],
      engine: "Tesseract (demo)", validated: false, needsSpecialist: true },
  }),
  makeAsset("adm-009", {
    kind: "document", fileName: "demo-doc-01.pdf", mime: "application/pdf",
    lifecycle: "uploaded",
    metadata: { documentId: "adm-009", title: "Demo document 01", date: null, language: "en",
      type: "writing", topic: ["education", "published works"], collection: "Demo Collection C",
      source: "Demo source — not verified", keywords: ["education", "published"],
      accessRights: "open", rightsNote: "Demo", provenanceNote: "Demo", completeness: 25 },
  }),
  makeAsset("adm-010", {
    kind: "scan", fileName: "demo-scan-06.jpg", lifecycle: "approved",
    checksum: { algo: "SHA-256", hex: "e".repeat(64), computedAt: now },
    metadata: { documentId: "adm-010", title: "Demo archival document 06", date: null, language: "en",
      type: "record", topic: ["archival record"], collection: "Demo Collection A",
      source: "Demo source — not verified", keywords: ["record", "archival"],
      accessRights: "open", rightsNote: "Demo", provenanceNote: "Demo", completeness: 85 },
    ocr: { status: "done", text: "Approved demo scan record.", wordConfidence: [],
      engine: "Tesseract (demo)", validated: true, needsSpecialist: false },
  }),
  makeAsset("adm-011", {
    kind: "audio", fileName: "demo-audio-02.mp3", mime: "audio/mp3",
    lifecycle: "published",
    checksum: { algo: "SHA-256", hex: "f".repeat(64), computedAt: now },
    metadata: { documentId: "adm-011", title: "Demo audio record 02", date: null, language: "hi",
      type: "speech", topic: ["public address", "social rights"], collection: "Demo Collection B",
      source: "Demo source — not verified", keywords: ["audio", "speech", "hindi"],
      accessRights: "open", rightsNote: "Demo", provenanceNote: "Demo", completeness: 95 },
  }),
  makeAsset("adm-012", {
    kind: "video", fileName: "demo-video-02.mp4", mime: "video/mp4",
    lifecycle: "ocr-queued",
    metadata: { documentId: "adm-012", title: "Demo video record 02", date: null, language: "en",
      type: "video", topic: ["constitutional assembly"], collection: "Demo Collection C",
      source: "Demo source — not verified", keywords: ["video", "assembly"],
      accessRights: "restricted", rightsNote: "Demo restricted", provenanceNote: "Demo", completeness: 15 },
  }),
];

export const SEED_ACTIVITY: ActivityLogEntry[] = [
  { id: "log-001", at: now, role: "archivist",     action: "upload",    targetId: "adm-001", detail: "Uploaded demo-scan-01.jpg" },
  { id: "log-002", at: now, role: "archivist",     action: "ocr-run",   targetId: "adm-001", detail: "OCR completed (Tesseract)" },
  { id: "log-003", at: now, role: "reviewer",      action: "approve",   targetId: "adm-001", detail: "Approved for publication" },
  { id: "log-004", at: now, role: "administrator", action: "publish",   targetId: "adm-001", detail: "Published to public archive" },
  { id: "log-005", at: now, role: "reviewer",      action: "reject",    targetId: "adm-007", detail: "Incomplete metadata" },
  { id: "log-006", at: now, role: "archivist",     action: "upload",    targetId: "adm-009", detail: "Uploaded demo-doc-01.pdf" },
];
